name = "All The Leisures"
author = "atl-team"
version = "1.0.1b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43f9c8c1ddf3ecd4f84a8396c197d68a1bb3cf6ce93e4e3673cf45d3486e78b1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.241"
