name = "All The Leisures"
author = "atl-team"
version = "1.0.1b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c73f15bd0b28f9a262ad4dd47344ae87e1b2d58ac3ad7c86a99a196433c5433"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.241"
