let $Player = Java.loadClass("net.minecraft.world.entity.player.Player")

StartupEvents.registry('item', event => {
  event.create('flying_soul')
  .maxStackSize(1)
  .tooltip("§5§l飞行大师的灵魂")
  .tooltip("§d来自异世界的飞行大师之魂无法在这里施展出全部力量")
  .tooltip("§d但即使只是他的一片羽毛")
  .tooltip("§d带动你的飞行也是绰绰有余")
  .tooltip("")
  .tooltip("§6装备于腰带时")
  .tooltip("§e获得无限制的缓降效果")
  .tooltip("§d允许你进行创造飞行，无消耗经验等限制条件")
  .tooltip("§d取下时会直接取消飞行")
  .tooltip("§7§m看着很像...但真的是店员鸡的一根羽毛吗？")
  .rarity("epic")
})
StartupEvents.registry('item', event => {
  event.create('silver_chicken')
  .maxStackSize(1)
  .tooltip("§l银色店员鸡")
  .tooltip("完成了部分章节的奖励")
  .tooltip("它也许可以带你飞起来？")
  .tooltip("不，它太小了，没办法让你自由飞行呢")
  .rarity("common")
})
StartupEvents.registry('item', event => {
  event.create('golden_chicken')
  .maxStackSize(1)
  .tooltip("§e§l金色店员鸡")
  .tooltip("§e完成了部分章节的奖励")
  .tooltip("§e它还是没有足够的力量让你飞起来")
  .rarity("uncommon")
})
