#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Compare workspace config against a clean generated instance config.

Modes are intentionally split so each cleanup rule can be committed separately:
  1. remove tracked workspace configs that are identical to clean instance configs
  2. report same-path configs whose contents differ
  3. report configs generated by the instance but missing in workspace
  4. remove workspace-only configs unless they belong to a shared config root
     or look server-only
"""

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

try:
    import tomllib
except ImportError:  # pragma: no cover
    import tomli as tomllib


sys.stdout.reconfigure(encoding="utf-8", errors="replace")
sys.stderr.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parent.parent
WORK_CONFIG = ROOT / "config"
INSTANCE_CONFIG = Path(r"D:\Minecraft\.minecraft\versions\All The Leisures\config")
SERVER_MODS = Path(r"C:\Users\UuWuZhi\Downloads\mods\mods")
CLIENT_MODS = Path(r"C:\Users\UuWuZhi\Downloads\All The Leisures v1.0.2a\overrides\mods")
REPORT_DIR = ROOT / "docs" / "maintenance" / "config-cleanup"

# Mods added during the previous mod sync task. Instance-only configs matching
# these are expected and should not require workspace action.
RECENT_MOD_SIGNALS = {
    "distanthorizons",
    "kubejsadditions",
    "kubejsjei",
    "kubejei",
    "spark",
    "ssrd",
}

# Some mods store authored pack content under config, but may not regenerate
# their folder on a fresh launch unless the feature/editor is opened.
AUTHORED_CONFIG_ROOTS = {
    "ftbquests",
}


def rel_key(path, base):
    return path.relative_to(base).as_posix().casefold()


def sha256(path):
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def files_under(base):
    if not base.is_dir():
        raise SystemExit(f"目录不存在: {base}")
    return {rel_key(path, base): path for path in base.rglob("*") if path.is_file()}


def read_toml(path):
    with path.open("rb") as fh:
        return tomllib.load(fh)


def tracked_config_keys():
    result = subprocess.run(
        ["git", "ls-files", "config"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=True,
    )
    return {line.strip().casefold() for line in result.stdout.splitlines() if line.strip()}


def normalize_signal(value):
    return re.sub(r"[^a-z0-9]+", "", value.casefold())


def strip_jar_prefix(name):
    # Client jars often have Chinese labels like "[玉] Jade-...jar"; keep the real suffix too.
    if "]" in name:
        return name.rsplit("]", 1)[1].strip()
    return name


def jar_hashes(path):
    hashes = {}
    for alg in ("sha1", "sha512"):
        h = hashlib.new(alg)
        with path.open("rb") as fh:
            for chunk in iter(lambda: fh.read(1024 * 1024), b""):
                h.update(chunk)
        hashes[alg] = h.hexdigest()
    return hashes


def jar_identity(path, side):
    info = {"side": side, "path": path, "name": path.name}
    info.update(jar_hashes(path))
    return info


def local_mods():
    mods = []
    for side, folder in (("server", SERVER_MODS), ("client", CLIENT_MODS)):
        if not folder.is_dir():
            continue
        for path in folder.glob("*.jar"):
            mods.append(jar_identity(path, side))
    return mods


def workspace_mod_metadata():
    metas = []
    mods_dir = ROOT / "mods"
    for path in sorted(mods_dir.glob("*.pw.toml")):
        try:
            meta = read_toml(path)
        except Exception:
            continue
        metas.append(
            {
                "path": path,
                "name": meta.get("name", path.stem),
                "filename": meta.get("filename", ""),
                "side": meta.get("side", "both"),
                "hash_format": meta.get("download", {}).get("hash-format"),
                "hash": meta.get("download", {}).get("hash"),
            }
        )
    return metas


def metadata_presence(meta, mods):
    present = set()
    filename = meta["filename"]
    for loc in mods:
        fmt = meta["hash_format"]
        hv = meta["hash"]
        if fmt in ("sha1", "sha512") and hv and loc.get(fmt) == hv:
            present.add(loc["side"])
        elif filename:
            loc_name = loc["name"].casefold()
            want = filename.casefold()
            if loc_name == want or loc_name.endswith(want):
                present.add(loc["side"])
    return present


def extract_mod_ids(jar_path):
    ids = set()
    try:
        with zipfile.ZipFile(jar_path) as zf:
            for name in ("META-INF/neoforge.mods.toml", "META-INF/mods.toml"):
                if name in zf.namelist():
                    try:
                        data = tomllib.loads(zf.read(name).decode("utf-8", "replace"))
                    except Exception:
                        data = {}
                    for item in data.get("mods", []):
                        mod_id = item.get("modId")
                        if mod_id:
                            ids.add(mod_id)
            if "fabric.mod.json" in zf.namelist():
                try:
                    data = json.loads(zf.read("fabric.mod.json").decode("utf-8", "replace"))
                    if data.get("id"):
                        ids.add(data["id"])
                except Exception:
                    pass
    except zipfile.BadZipFile:
        pass
    return ids


def server_only_signals():
    mods = local_mods()
    metas = workspace_mod_metadata()
    signals = set()

    for meta in metas:
        if meta["side"] == "server":
            for value in (meta["name"], meta["filename"], meta["path"].stem):
                sig = normalize_signal(value)
                if len(sig) >= 4:
                    signals.add(sig)

    for loc in mods:
        if loc["side"] != "server":
            continue
        in_client = any(
            other["side"] == "client"
            and (other["sha1"] == loc["sha1"] or other["name"].casefold().endswith(strip_jar_prefix(loc["name"]).casefold()))
            for other in mods
        )
        if in_client:
            continue
        for value in (loc["name"], strip_jar_prefix(loc["name"]), loc["path"].stem):
            sig = normalize_signal(value)
            if len(sig) >= 4:
                signals.add(sig)
        for mod_id in extract_mod_ids(loc["path"]):
            sig = normalize_signal(mod_id)
            if len(sig) >= 4:
                signals.add(sig)

    return signals


def classify_by_signals(rel_path, signals):
    norm = normalize_signal(rel_path)
    matches = sorted(sig for sig in signals if len(sig) >= 4 and sig in norm)
    return matches


def compare():
    work = files_under(WORK_CONFIG)
    instance = files_under(INSTANCE_CONFIG)
    tracked = tracked_config_keys()

    shared = sorted(set(work) & set(instance))
    identical = [key for key in shared if sha256(work[key]) == sha256(instance[key]) and f"config/{key}" in tracked]
    modified = [key for key in shared if sha256(work[key]) != sha256(instance[key])]
    instance_only = sorted(set(instance) - set(work))
    workspace_only = sorted(key for key in set(work) - set(instance) if f"config/{key}" in tracked)
    return work, instance, identical, modified, instance_only, workspace_only


def top_config_root(key):
    if "/" in key:
        return key.split("/", 1)[0]
    return None


def shared_config_roots(work, instance):
    work_roots = {root for root in (top_config_root(key) for key in work) if root}
    instance_roots = {root for root in (top_config_root(key) for key in instance) if root}
    return work_roots & instance_roots


def write_report(name, title, rows, extra=None):
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    path = REPORT_DIR / name
    lines = [f"# {title}", "", f"Count: {len(rows)}", ""]
    if extra:
        lines.extend(extra)
        lines.append("")
    for row in rows:
        if isinstance(row, str):
            lines.append(f"- `{row}`")
        else:
            lines.append("- " + " | ".join(f"`{item}`" for item in row))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"写入报告: {path.relative_to(ROOT)}")
    return path


def report_keys(name):
    path = REPORT_DIR / name
    if not path.exists():
        return set()
    keys = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        match = re.match(r"- `([^`]+)`", line)
        if match:
            keys.add(match.group(1).casefold())
    return keys


def remove_files(paths):
    removed = []
    for path in paths:
        if path.exists():
            path.unlink()
            removed.append(path)
    for folder in sorted({p.parent for p in removed}, key=lambda p: len(p.parts), reverse=True):
        cur = folder
        while cur != WORK_CONFIG and cur.is_dir():
            try:
                cur.rmdir()
            except OSError:
                break
            cur = cur.parent
    return removed


def condition1():
    work, _instance, identical, _modified, _instance_only, _workspace_only = compare()
    rows = [(key, sha256(work[key])) for key in identical]
    removed = remove_files([work[key] for key in identical])
    write_report(
        "01-identical-removed.md",
        "Condition 1 - Identical Tracked Configs Removed",
        rows,
        ["These files existed in both config folders with identical bytes and were removed from workspace tracking."],
    )
    print(f"删除同名同内容配置: {len(removed)}")


def condition2():
    work, instance, _identical, modified, _instance_only, _workspace_only = compare()
    rows = [(key, sha256(work[key]), sha256(instance[key])) for key in modified]
    write_report(
        "02-modified-required.md",
        "Condition 2 - Required Configs Modified In Workspace",
        rows,
        ["Columns: relative path | workspace sha256 | clean instance sha256"],
    )
    print(f"同名但内容不同配置: {len(rows)}")


def condition3():
    _work, instance, _identical, _modified, instance_only, _workspace_only = compare()
    already_removed_defaults = report_keys("01-identical-removed.md")
    instance_only = [key for key in instance_only if key.casefold() not in already_removed_defaults]
    rows = []
    unconfirmed = []
    for key in instance_only:
        matches = classify_by_signals(key, RECENT_MOD_SIGNALS)
        status = "recent-mod" if matches else "unconfirmed"
        if not matches:
            unconfirmed.append(key)
        rows.append((key, status, ",".join(matches) if matches else "-"))
    write_report(
        "03-instance-only.md",
        "Condition 3 - Instance Generated Configs Missing In Workspace",
        rows,
        ["Columns: relative path | classification | matched signal"],
    )
    print(f"实例新增配置: {len(rows)}; 无法确认: {len(unconfirmed)}")


def condition4():
    work, instance, _identical, _modified, _instance_only, workspace_only = compare()
    shared_roots = shared_config_roots(work, instance)
    signals = server_only_signals()
    delete_keys = []
    keep_rows = []
    delete_rows = []
    for key in workspace_only:
        root = top_config_root(key)
        if root and root in shared_roots:
            keep_rows.append((key, "shared-root-extra", root))
            continue
        if root and root in AUTHORED_CONFIG_ROOTS:
            keep_rows.append((key, "authored-root-extra", root))
            continue

        matches = classify_by_signals(key, signals)
        if matches:
            keep_rows.append((key, "server-only-candidate", ",".join(matches[:8])))
        else:
            delete_keys.append(key)
            delete_rows.append((key, "deleted", "-"))

    removed = remove_files([work[key] for key in delete_keys])
    rows = delete_rows + keep_rows
    write_report(
        "04-workspace-only-cleanup.md",
        "Condition 4 - Workspace-Only Config Cleanup",
        rows,
        [
            "Workspace-only configs under a config root that exists in both workspace and instance were retained.",
            "Workspace-only configs with server-only signals were retained.",
            "Only remaining workspace-only configs were deleted.",
        ],
    )
    print(f"工作区独有配置: {len(workspace_only)}; 删除: {len(removed)}; 保留: {len(keep_rows)}")


def summary():
    _work, _instance, identical, modified, instance_only, workspace_only = compare()
    rows = [
        ("identical tracked", str(len(identical))),
        ("modified shared", str(len(modified))),
        ("instance only", str(len(instance_only))),
        ("workspace only tracked", str(len(workspace_only))),
    ]
    write_report("00-summary.md", "Config Cleanup Summary", rows)


def main():
    parser = argparse.ArgumentParser(description="Compare and clean config files.")
    parser.add_argument("condition", choices=["summary", "1", "2", "3", "4"])
    args = parser.parse_args()

    if args.condition == "summary":
        summary()
    elif args.condition == "1":
        condition1()
    elif args.condition == "2":
        condition2()
    elif args.condition == "3":
        condition3()
    elif args.condition == "4":
        condition4()


if __name__ == "__main__":
    main()
